In [4]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

In [5]:
len(annotations), len(set(annotations))

(317, 317)

In [6]:
import numpy as np
from lapin import lapin
from faddis_zhirayr import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    tc = np.loadtxt("corelevance_matrix.txt")
    print(tc.shape)

    tc_transformed = lapin(tc)
    B, member, contrib, intensity, lat, tt = faddis(tc_transformed)
    np.savetxt("clusters.dat", member)
    print(member.shape)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for i, cluster in enumerate(np.round(member.T, 3)):
        print("CLUSTER {}:\n".format(i + 1))
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])
        print("\n\n")

(317, 317)
Cluster contribution is too small
(317, 14)
CLUSTER 1:

[('query representation', 0.949), ('distributed database recovery', 0.295), ('data locking', 0.108), ('reinforcement learning theory', 0.005), ('web log analysis', 0.004), ('multi-agent learning', 0.003), ('language models', 0.003), ('learning to rank', 0.003), ('supervised learning by classification', 0.003), ('active learning', 0.002), ('network data models', 0.002), ('document structure', 0.002), ('video segmentation', 0.002), ('topic modeling', 0.002), ('online learning settings', 0.002)]



CLUSTER 2:

[('active learning settings', 0.647), ('online learning theory', 0.535), ('multi-agent reinforcement learning', 0.518), ('query learning', 0.143), ('inverse reinforcement learning', 0.046), ('learning to rank', 0.036), ('mixture modeling', 0.02), ('lifelong machine learning', 0.017), ('statistical relational learning', 0.015), ('object detection', 0.014), ('speech recognition', 0.013), ('online analytical processing 

In [2]:
contrib

array([0.0031149 , 0.00300115, 0.00290139, 0.00277625, 0.00269503,
       0.00263296, 0.00255424, 0.0025022 , 0.00244303, 0.00240134,
       0.00231523, 0.00223002, 0.00207853, 0.00199784])

In [3]:
intensity

matrix([[0.9962047 , 0.9924238 ],
        [0.98698267, 0.9741348 ],
        [0.97867627, 0.95780724],
        [0.96794869, 0.93692466],
        [0.96078993, 0.92311729],
        [0.95520918, 0.91242458],
        [0.94798803, 0.89868131],
        [0.9431225 , 0.88948004],
        [0.93749677, 0.87890019],
        [0.93347154, 0.87136911],
        [0.92498823, 0.85560322],
        [0.91635705, 0.83971024],
        [0.90038153, 0.81068691],
        [0.89151254, 0.79479461]])

In [4]:
lat

array([1.00000002, 1.00000015, 1.00000032, 1.005582  , 1.0000049 ,
       1.00110879, 1.00019845, 1.00000003, 1.00313359, 1.00000098,
       1.00099506, 1.00378217, 1.00178688, 1.00090281])

In [5]:
tc

array([[2305.0814415 , 3051.74081109, 2419.97985005, ..., 2702.02572888,
        1833.74858063, 2071.55138414],
       [3051.74081109, 4458.59457895, 3484.23240944, ..., 3903.01060014,
        2493.31161151, 2957.11046645],
       [2419.97985005, 3484.23240944, 2935.31079589, ..., 3104.19581913,
        1979.45360701, 2357.2419839 ],
       ...,
       [2702.02572888, 3903.01060014, 3104.19581913, ..., 3791.35716949,
        2209.7986961 , 2656.0674004 ],
       [1833.74858063, 2493.31161151, 1979.45360701, ..., 2209.7986961 ,
        1662.18167924, 1706.75366935],
       [2071.55138414, 2957.11046645, 2357.2419839 , ..., 2656.0674004 ,
        1706.75366935, 2254.21414074]])

In [6]:
np.linalg.eigh(tc)[0][::-1]

array([6.14806125e+05, 2.94476028e+03, 2.74563326e+03, 2.62436189e+03,
       2.02967532e+03, 1.92706980e+03, 1.85074257e+03, 1.82368666e+03,
       1.43701574e+03, 1.35390206e+03, 1.12456386e+03, 1.05698324e+03,
       1.02216606e+03, 9.76450849e+02, 8.84878841e+02, 8.15280263e+02,
       7.81835859e+02, 7.31321415e+02, 7.14352494e+02, 6.82892432e+02,
       6.71866106e+02, 5.72060566e+02, 5.56350591e+02, 5.48160323e+02,
       5.36251179e+02, 5.22039841e+02, 5.00172882e+02, 4.87716133e+02,
       4.65557050e+02, 4.55694087e+02, 4.43543852e+02, 4.33244907e+02,
       4.19490312e+02, 4.14999532e+02, 4.05246632e+02, 3.98248694e+02,
       3.80761613e+02, 3.62362772e+02, 3.52562176e+02, 3.35754934e+02,
       3.29620694e+02, 3.26763627e+02, 3.05827061e+02, 3.00701110e+02,
       2.89714853e+02, 2.88189012e+02, 2.83014895e+02, 2.73388672e+02,
       2.67739992e+02, 2.57634808e+02, 2.54888677e+02, 2.50398648e+02,
       2.43121980e+02, 2.41566665e+02, 2.34832228e+02, 2.29120968e+02,
      

In [7]:
np.linalg.eigh(tc)[0][::-1][0] / np.linalg.eigh(tc)[0][::-1][-1]

1.622153172632381e+18

In [ ]:
def laplace_transform(matrix):
    row_sums = np.sum(matrix, axis=0)



















In [48]:
A = np.array([[1, 3], [3, 6]])

In [49]:
A

array([[1, 3],
       [3, 6]])

In [50]:
A_cols = np.sum(A, axis=1)

In [51]:
A_cols, np.sqrt(A_cols)

(array([4, 9]), array([2., 3.]))

In [52]:
A / np.sqrt(A_cols)[:, None] / np.sqrt(A_cols)

array([[0.25      , 0.5       ],
       [0.5       , 0.66666667]])

In [56]:
sum_cols_sqrt = np.sqrt(np.sum(tc, axis=0))

In [57]:
tc_1 = tc / sum_cols_sqrt[:, None] / sum_cols_sqrt

In [59]:
tc_2 = np.eye(len(tc)) - tc_1

In [60]:
np.linalg.eigh(tc_2)[0][::-1]

array([1.00000000e+00, 9.99999984e-01, 9.99999854e-01, 9.99999681e-01,
       9.99999411e-01, 9.99999295e-01, 9.99999203e-01, 9.99999155e-01,
       9.99999041e-01, 9.99998852e-01, 9.99998677e-01, 9.99998368e-01,
       9.99998057e-01, 9.99997872e-01, 9.99997735e-01, 9.99997636e-01,
       9.99997606e-01, 9.99997478e-01, 9.99997197e-01, 9.99997057e-01,
       9.99996980e-01, 9.99996777e-01, 9.99996517e-01, 9.99996388e-01,
       9.99996095e-01, 9.99995985e-01, 9.99995805e-01, 9.99995728e-01,
       9.99995516e-01, 9.99995415e-01, 9.99995073e-01, 9.99994822e-01,
       9.99994611e-01, 9.99994244e-01, 9.99993709e-01, 9.99993437e-01,
       9.99993327e-01, 9.99993137e-01, 9.99992988e-01, 9.99992855e-01,
       9.99992436e-01, 9.99992042e-01, 9.99991675e-01, 9.99991460e-01,
       9.99991236e-01, 9.99991044e-01, 9.99990808e-01, 9.99990300e-01,
       9.99990087e-01, 9.99989891e-01, 9.99989088e-01, 9.99989010e-01,
       9.99988626e-01, 9.99988364e-01, 9.99987801e-01, 9.99987626e-01,
      

In [65]:
1 / 9.94373695e-01

1.0056581394180988

In [8]:
np.linalg.eigh(lapin(tc))[0][::-1]

array([1.00565814e+00, 1.00471718e+00, 1.00380051e+00, 1.00376586e+00,
       1.00333809e+00, 1.00315287e+00, 1.00281793e+00, 1.00263133e+00,
       1.00227379e+00, 1.00195386e+00, 1.00184711e+00, 1.00182035e+00,
       1.00174200e+00, 1.00155708e+00, 1.00135567e+00, 1.00134468e+00,
       1.00133233e+00, 1.00126414e+00, 1.00120822e+00, 1.00113845e+00,
       1.00110976e+00, 1.00104842e+00, 1.00100322e+00, 1.00096274e+00,
       1.00092248e+00, 1.00091354e+00, 1.00089534e+00, 1.00088008e+00,
       1.00085788e+00, 1.00084628e+00, 1.00080316e+00, 1.00078019e+00,
       1.00073982e+00, 1.00073663e+00, 1.00071978e+00, 1.00068180e+00,
       1.00066275e+00, 1.00062245e+00, 1.00061378e+00, 1.00060677e+00,
       1.00059156e+00, 1.00058402e+00, 1.00055688e+00, 1.00054197e+00,
       1.00052596e+00, 1.00052218e+00, 1.00049998e+00, 1.00049099e+00,
       1.00048170e+00, 1.00047745e+00, 1.00046721e+00, 1.00046072e+00,
       1.00043845e+00, 1.00043596e+00, 1.00042123e+00, 1.00040456e+00,
      

In [9]:
np.savetxt("corelevance_matrix_lapin.txt", tc_transformed)

In [10]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [11]:
member = np.loadtxt("clusters.dat")

In [12]:
member.shape

(317, 14)

In [13]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

CLUSTER:

[('query representation', 0.9492738808638721), ('distributed database recovery', 0.2952466254141227), ('data locking', 0.10766606850706567), ('reinforcement learning theory', 0.004788322615586317), ('web log analysis', 0.0035142409368013098), ('multi-agent learning', 0.0032362405117119467), ('learning to rank', 0.0029917827381894125), ('language models', 0.002930889077737563), ('supervised learning by classification', 0.002519422410168774), ('online learning settings', 0.0023864710609815547), ('network data models', 0.0017331426620566376), ('active learning', 0.001682660905651917), ('document structure', 0.0016760969324413695), ('video segmentation', 0.0016273449249671603), ('topic modeling', 0.0016255370971410311)]



CLUSTER:

[('active learning settings', 0.646887145506174), ('online learning theory', 0.5350419077372148), ('multi-agent reinforcement learning', 0.5177446381440173), ('query learning', 0.14309190122171475), ('inverse reinforcement learning', 0.046179521538707

In [14]:
member.T

array([[0.00040891, 0.00013549, 0.00086322, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00168112, 0.00373514, ..., 0.00038837, 0.        ,
        0.        ],
       [0.        , 0.00549358, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.0785389 , 0.        , 0.        , ..., 0.        , 0.04744748,
        0.        ],
       [0.        , 0.        , 0.00223931, ..., 0.00664991, 0.        ,
        0.00211133],
       [0.0115795 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00426337]])

In [15]:
np.max(member)

0.9492738808638721

In [16]:
np.min(member)

0.0

In [17]:
np.histogram(member.flatten())

(array([4290,   78,   29,   20,    7,    4,    4,    1,    2,    3]),
 array([0.        , 0.09492739, 0.18985478, 0.28478216, 0.37970955,
        0.47463694, 0.56956433, 0.66449172, 0.7594191 , 0.85434649,
        0.94927388]))

In [18]:
def get_print_top_k_list(U, top_k=10):
    _, n_cl = U.shape
    top_k_list = []
    for i in range(n_cl):
        top_k_list.append(np.argsort(U[: ,i])[::-1][:top_k])
        print(top_k_list[i])
    return top_k_list

In [19]:
top_k_list = get_print_top_k_list(member)

[159 103  91  12 148   8 172 170 245 266]
[270   7 260  10 258 172 251 263 281 235]
[243 285  18 232 155 195 225 287 252 175]
[148 290 249   5 161  59 149  58 180 143]
[246 129 279 218 235  22   5 175 169 314]
[220 156 230 222 226  54 225 169 304 111]
[ 81 102  86 231  94 146 112  84 214  95]
[103  91 279 108 161 270  12   8 251  71]
[247  90 151  73  11 190 239  54 107  22]
[ 10 287  97 134 266 152 290 183  36 233]
[150 254 236 218  57 140 229  39  15  93]
[ 26  30  25 223 303  71 287  88  90 164]
[271 298 278  64 119 309 136  23 170 183]
[238 244 225 257 169 101  91 100  28 236]


In [20]:
def print_intersections(top_k_list):
    print('\t\t Intersections')
    for i in range(len(top_k_list)):
        print(f'Cluster {i+1}', end='\t')
        intersections = ''
        for j in range(len(top_k_list )):
            n_common = len(set(top_k_list[i]).intersection(set(top_k_list[j])))
            intersections += f'{n_common} --'
        intersections.strip('-')
        intersections.strip('-')    
        print(intersections)

In [21]:
print_intersections(top_k_list)

		 Intersections
Cluster 1	10 --1 --0 --1 --0 --0 --0 --4 --0 --1 --0 --0 --1 --1 --
Cluster 2	1 --10 --0 --0 --1 --0 --0 --2 --0 --1 --0 --0 --0 --0 --
Cluster 3	0 --0 --10 --0 --1 --1 --0 --0 --0 --1 --0 --1 --0 --1 --
Cluster 4	1 --0 --0 --10 --1 --0 --0 --1 --0 --1 --0 --0 --0 --0 --
Cluster 5	0 --1 --1 --1 --10 --1 --0 --1 --1 --0 --1 --0 --0 --1 --
Cluster 6	0 --0 --1 --0 --1 --10 --0 --0 --1 --0 --0 --0 --0 --2 --
Cluster 7	0 --0 --0 --0 --0 --0 --10 --0 --0 --0 --0 --0 --0 --0 --
Cluster 8	4 --2 --0 --1 --1 --0 --0 --10 --0 --0 --0 --1 --0 --1 --
Cluster 9	0 --0 --0 --0 --1 --1 --0 --0 --10 --0 --0 --1 --0 --0 --
Cluster 10	1 --1 --1 --1 --0 --0 --0 --0 --0 --10 --0 --1 --1 --0 --
Cluster 11	0 --0 --0 --0 --1 --0 --0 --0 --0 --0 --10 --0 --0 --1 --
Cluster 12	0 --0 --1 --0 --0 --0 --0 --1 --1 --1 --0 --10 --0 --0 --
Cluster 13	1 --0 --0 --0 --0 --0 --0 --0 --0 --1 --0 --0 --10 --0 --
Cluster 14	1 --0 --1 --0 --1 --2 --0 --1 --0 --0 --1 --0 --0 --10 --
