In [1]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

In [2]:
len(annotations), len(set(annotations))

(317, 317)

In [1]:
import numpy as np
from lapin import lapin
from faddis_zhirayr import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    tc = np.loadtxt("corelevance_matrix.txt")
    print(tc.shape)

    #tc_transformed = lapin(tc)
    B, member, contrib, intensity, lat, tt = faddis(tc)
    np.savetxt("clusters without lapin.dat", member)
    print(member.shape)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for i, cluster in enumerate(np.round(member.T, 3)):
        print("CLUSTER {}:\n".format(i + 1))
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])
        print("\n\n")

(317, 317)
Residual is too small
(317, 1)
CLUSTER 1:

[('active learning', 0.112), ('q-learning', 0.112), ('query learning', 0.1), ('batch learning', 0.096), ('models of learning', 0.094), ('statistical relational learning', 0.094), ('learning from demonstrations', 0.093), ('lifelong machine learning', 0.092), ('learning to rank', 0.091), ('representation', 0.091), ('transfer learning', 0.09), ('information extraction', 0.089), ('machine translation', 0.088), ('active learning settings', 0.088), ('supervised learning by classification', 0.087)]





In [2]:
! pip install scikit-network

Defaulting to user installation because normal site-packages is not writeable


In [3]:
from sknetwork.clustering import Louvain
louvain = Louvain(modularity="newman")
labels = louvain.fit_transform(tc)
len(set(labels))







27

In [4]:
labels

array([ 1,  0,  5,  0,  2,  3, 22,  0,  0,  2,  0,  6,  0,  0,  0, 18,  0,
        0,  2,  0,  0,  0, 14,  1,  0, 12, 12,  9, 11,  2, 12, 22, 16,  2,
        2,  1, 10, 10, 10, 18, 10,  1,  1,  1,  1,  0, 14,  2,  1,  7,  9,
        0,  0,  1, 14,  7,  3, 18,  3,  3,  0, 25, 16,  3, 11, 16, 17, 16,
        2,  2,  2,  2,  2,  6,  0,  0,  0,  2,  0,  4,  0,  0,  4,  4, 18,
        0,  0,  4,  1,  7, 14,  0,  0,  0, 24,  7,  0, 17,  0,  0,  0, 17,
       12, 17,  0,  3, 24,  6,  7,  0,  0,  1, 15,  0,  0, 26,  0,  0,  0,
        0,  1,  0, 10,  5,  5,  5,  5,  5,  5,  5,  4,  0,  9,  7,  5, 13,
       11,  1,  0,  0,  0,  5,  9,  3,  0,  0,  0,  4,  3,  3,  0,  6,  2,
        3,  1,  2, 23,  6,  0,  8,  7,  3,  7,  1,  1,  2,  4,  4,  1,  2,
        2,  6,  0,  4, 15,  0,  7,  5,  0,  1,  3,  4, 13, 20,  1, 13,  0,
        0,  1,  8,  6, 15, 15,  0,  4,  4,  0, 15,  4,  4,  4,  0,  0,  0,
        9,  9,  9,  1,  3,  1,  1,  1,  0,  1,  1,  0,  0,  1, 19,  0, 23,
        0,  1, 12,  0,  2

In [5]:
for i in range(len(set(labels))):
    print("\n\nCLUSTER {} ({} nodes):".format(i, np.sum(labels == i)))
    no = 0
    for j in range(len(labels)):
        if labels[j] == i:
            no += 1
            print(no, annotations[j])







CLUSTER 0 (98 nodes):
1 boolean function learning
2 support vector machines
3 online learning theory
4 multi-agent learning
5 query learning
6 reinforcement learning theory
7 active learning
8 semi-supervised learning
9 data exchange
10 data provenance
11 database query languages
12 database constraints theory
13 database interoperability
14 theory of database privacy and security
15 gibbs sampling
16 bootstrapping
17 jackknifing
18 renewal theory
19 data streams
20 incomplete data
21 temporal data
22 inconsistent data
23 data scans
24 point lookups
25 data encryption
26 record and block layout
27 data locking
28 transaction logging
29 database recovery
30 mapreduce-based systems
31 triggers and rules
32 database views
33 integrity checking
34 main memory engines
35 mapreduce languages
36 call level interfaces
37 wrappers
38 mediators and data integration
39 data warehouses
40 federated databases
41 data cleaning
42 item-based
43 interestingness
44 data stream mining
45 key-phrase in

In [6]:
louvain.membership_

<317x27 sparse matrix of type '<class 'numpy.float64'>'
	with 8559 stored elements in Compressed Sparse Row format>

In [7]:
louvain_membership = louvain.membership_.todense()

In [8]:
np.min(louvain_membership), np.max(louvain_membership)

(0.0033025143424369433, 0.3136629519508258)

In [12]:
louvain_membership[:, 0]

matrix([[0.3104943 ],
        [0.31184161],
        [0.31217753],
        [0.31227114],
        [0.31119098],
        [0.30861309],
        [0.31178555],
        [0.31237475],
        [0.31227921],
        [0.31198525],
        [0.31237858],
        [0.31022043],
        [0.31248673],
        [0.31245007],
        [0.3125794 ],
        [0.31151627],
        [0.31299203],
        [0.31261619],
        [0.31169331],
        [0.31273152],
        [0.31243363],
        [0.31240467],
        [0.31093524],
        [0.31064468],
        [0.31275657],
        [0.30984358],
        [0.3101258 ],
        [0.31091467],
        [0.31128478],
        [0.31032528],
        [0.3102663 ],
        [0.31116878],
        [0.31132289],
        [0.31087108],
        [0.31022869],
        [0.31070924],
        [0.30958785],
        [0.3112219 ],
        [0.31113698],
        [0.31086333],
        [0.31006682],
        [0.31104017],
        [0.311431  ],
        [0.31052668],
        [0.30985703],
        [0

In [13]:
for i, cluster in enumerate(np.round(louvain_membership.T, 3)):
    print("CLUSTER {}:\n".format(i + 1))
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")






CLUSTER 1:

[('tracking', 0.314), ('semi-supervised learning', 0.313), ('data exchange', 0.313), ('data provenance', 0.313), ('database query languages', 0.313), ('theory of database privacy and security', 0.313), ('bootstrapping', 0.313), ('jackknifing', 0.313), ('data streams', 0.313), ('temporal data', 0.313), ('data scans', 0.313), ('data locking', 0.313), ('database recovery', 0.313), ('mapreduce-based systems', 0.313), ('database views', 0.313)]



CLUSTER 2:

[('query optimization', 0.147), ('summarization', 0.146), ('expectation maximization', 0.145), ('text categorization', 0.145), ('personalization', 0.145), ('scientific visualization', 0.145), ('geographic visualization', 0.145), ('visualization toolkits', 0.145), ('sample complexity and generalization bounds', 0.144), ('database query processing and optimization', 0.144), ('data encoding and canonicalization', 0.144), ('information visualization', 0.144), ('empirical studies in visualization', 0.144), ('visualization design

In [14]:
contrib

array([0.99985079])

In [15]:
intensity

matrix([[   784.09573733, 614806.12530315]])

In [16]:
lat

array([614806.12530315])

In [17]:
tc

array([[2305.0814415 , 3051.74081109, 2419.97985005, ..., 2702.02572888,
        1833.74858063, 2071.55138414],
       [3051.74081109, 4458.59457895, 3484.23240944, ..., 3903.01060014,
        2493.31161151, 2957.11046645],
       [2419.97985005, 3484.23240944, 2935.31079589, ..., 3104.19581913,
        1979.45360701, 2357.2419839 ],
       ...,
       [2702.02572888, 3903.01060014, 3104.19581913, ..., 3791.35716949,
        2209.7986961 , 2656.0674004 ],
       [1833.74858063, 2493.31161151, 1979.45360701, ..., 2209.7986961 ,
        1662.18167924, 1706.75366935],
       [2071.55138414, 2957.11046645, 2357.2419839 , ..., 2656.0674004 ,
        1706.75366935, 2254.21414074]])

In [18]:
np.linalg.eigh(tc)[0][::-1]

array([6.14806125e+05, 2.94476028e+03, 2.74563326e+03, 2.62436189e+03,
       2.02967532e+03, 1.92706980e+03, 1.85074257e+03, 1.82368666e+03,
       1.43701574e+03, 1.35390206e+03, 1.12456386e+03, 1.05698324e+03,
       1.02216606e+03, 9.76450849e+02, 8.84878841e+02, 8.15280263e+02,
       7.81835859e+02, 7.31321415e+02, 7.14352494e+02, 6.82892432e+02,
       6.71866106e+02, 5.72060566e+02, 5.56350591e+02, 5.48160323e+02,
       5.36251179e+02, 5.22039841e+02, 5.00172882e+02, 4.87716133e+02,
       4.65557050e+02, 4.55694087e+02, 4.43543852e+02, 4.33244907e+02,
       4.19490312e+02, 4.14999532e+02, 4.05246632e+02, 3.98248694e+02,
       3.80761613e+02, 3.62362772e+02, 3.52562176e+02, 3.35754934e+02,
       3.29620694e+02, 3.26763627e+02, 3.05827061e+02, 3.00701110e+02,
       2.89714853e+02, 2.88189012e+02, 2.83014895e+02, 2.73388672e+02,
       2.67739992e+02, 2.57634808e+02, 2.54888677e+02, 2.50398648e+02,
       2.43121980e+02, 2.41566665e+02, 2.34832228e+02, 2.29120968e+02,
      

In [19]:
np.linalg.eigh(tc)[0][::-1][0] / np.linalg.eigh(tc)[0][::-1][-1]

1.622153172632381e+18

In [10]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [11]:
member = np.loadtxt("clusters without lapin.dat")

In [12]:
member.shape

(350, 9)

In [ ]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

In [13]:
member.T

array([[1.49838635e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.37093735e-04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.01744207e-03, 0.00000000e+00, 5.89176534e-03, ...,
        0.00000000e+00, 1.83503682e-02, 0.00000000e+00],
       ...,
       [1.57534014e-03, 8.93698229e-02, 1.09235694e-01, ...,
        1.22013114e-01, 4.53703247e-03, 0.00000000e+00],
       [5.43883551e-03, 2.60613864e-03, 0.00000000e+00, ...,
        1.81342689e-01, 6.91636500e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 2.18123304e-02]])

In [14]:
np.max(member)

0.9998084428690137

In [15]:
np.min(member)

0.0

In [16]:
np.histogram(member.flatten())

(array([3062,   54,   16,    8,    2,    1,    3,    1,    1,    2]),
 array([0.        , 0.09998084, 0.19996169, 0.29994253, 0.39992338,
        0.49990422, 0.59988507, 0.69986591, 0.79984675, 0.8998276 ,
        0.99980844]))

In [17]:
def get_print_top_k_list(U, top_k=10):
    _, n_cl = U.shape
    top_k_list = []
    for i in range(n_cl):
        top_k_list.append(np.argsort(U[: ,i])[::-1][:top_k])
        print(top_k_list[i])
    return top_k_list

In [18]:
top_k_list = get_print_top_k_list(member)

[  4  79  72 139 176 135  83 106  88 122]
[ 80  68  53 247 106  83 291   9 202 135]
[139 176 130 122  78 171 247 174 107 135]
[ 39 266 264 268 263 269 265 224 262 227]
[ 79  53 122  72 130  83 146 106 247   9]
[211 247 216 106 177 131 125 330 169 262]
[183 146 334 103 278 325 255 180 169 307]
[ 10  89 109 130 347 125  79 211 193 345]
[251  29 252  56  72 215  73 255  68  59]


In [19]:
def print_intersections(top_k_list):
    print('\t\t Intersections')
    for i in range(len(top_k_list)):
        print(f'Cluster {i+1}', end='\t')
        intersections = ''
        for j in range(len(top_k_list )):
            n_common = len(set(top_k_list[i]).intersection(set(top_k_list[j])))
            intersections += f'{n_common} --'
        intersections.strip('-')
        intersections.strip('-')    
        print(intersections)

In [20]:
print_intersections(top_k_list)

		 Intersections
Cluster 1	10 --3 --4 --0 --5 --1 --0 --1 --1 --
Cluster 2	3 --10 --2 --0 --5 --2 --0 --0 --1 --
Cluster 3	4 --2 --10 --0 --3 --1 --0 --1 --0 --
Cluster 4	0 --0 --0 --10 --0 --1 --0 --0 --0 --
Cluster 5	5 --5 --3 --0 --10 --2 --1 --2 --1 --
Cluster 6	1 --2 --1 --1 --2 --10 --1 --2 --0 --
Cluster 7	0 --0 --0 --0 --1 --1 --10 --0 --1 --
Cluster 8	1 --0 --1 --0 --2 --2 --0 --10 --0 --
Cluster 9	1 --1 --0 --0 --1 --0 --1 --0 --10 --
