In [1]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

In [2]:
len(annotations), len(set(annotations))

(343, 343)

In [3]:
import numpy as np
from lapin import lapin
from faddis_zhirayr import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    tc = np.loadtxt("corelevance_matrix.txt")
    print(tc.shape)

    B, member, contrib, intensity, lat, tt = faddis(tc)
    np.savetxt("clusters without lapin.dat", member)
    print(member.shape)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for i, cluster in enumerate(np.round(member.T, 3)):
        print("CLUSTER {}:\n".format(i + 1))
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])
        print("\n\n")

(343, 343)
Residual is too small
(343, 1)
CLUSTER 1:

[('computational learning', 0.115), ('detection information communication', 0.092), ('applications set', 0.086), ('modulation demodulation information communication', 0.086), ('approximation', 0.085), ('medical applications', 0.083), ('approximation functions', 0.08), ('partition relations', 0.079), ('differential equations', 0.079), ('applications statistics', 0.079), ('image processing compression reconstruction information communication', 0.079), ('graph intersection representations', 0.078), ('artificial neural networks deep learning', 0.078), ('difference equations', 0.077), ('communication networks', 0.076)]





In [4]:
np.linalg.eigh(tc)[0][::-1]

array([9.03996020e+05, 4.20177077e+03, 3.53479355e+03, 3.13773819e+03,
       2.94117148e+03, 2.85488008e+03, 2.51979707e+03, 2.33462507e+03,
       2.11598256e+03, 1.95511311e+03, 1.91221581e+03, 1.74948138e+03,
       1.54002986e+03, 1.48905705e+03, 1.41960020e+03, 1.39476157e+03,
       1.33015034e+03, 1.27906181e+03, 1.21455536e+03, 1.10998730e+03,
       1.05102270e+03, 1.01385712e+03, 1.00801730e+03, 9.69153267e+02,
       9.04981616e+02, 8.87650509e+02, 8.72385184e+02, 8.42372565e+02,
       7.85415993e+02, 7.68649270e+02, 7.50828293e+02, 7.01168528e+02,
       6.73565060e+02, 6.22299098e+02, 5.93948606e+02, 5.71457363e+02,
       5.64745076e+02, 5.10920605e+02, 4.98094595e+02, 4.86928760e+02,
       4.77794312e+02, 4.53842473e+02, 4.29211485e+02, 4.23627239e+02,
       4.20833577e+02, 4.12702442e+02, 3.93018069e+02, 3.80945415e+02,
       3.69304499e+02, 3.55473065e+02, 3.34425040e+02, 3.26954334e+02,
       3.08973771e+02, 3.06365667e+02, 3.01978128e+02, 2.93587966e+02,
      

In [4]:
! pip install scikit-network

Defaulting to user installation because normal site-packages is not writeable


In [5]:
from sknetwork.clustering import Louvain
louvain = Louvain(modularity="newman")
labels = louvain.fit_transform(tc)
len(set(labels))







18

In [6]:
labels

array([13,  2,  2,  8,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  0,  0,  0,  1,  1,  0,  1,  1,  0,  0,  1,
        1,  1,  1,  1,  2,  1,  1,  0,  0, 10,  8, 13, 11,  0,  0, 12,  0,
        8,  8,  0, 12,  7,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
        0,  0,  0,  0,  0,  8,  3,  8,  5,  5,  5,  5,  0,  0,  0,  0,  0,
        0, 13, 13, 13,  0,  0,  9,  9,  0,  0,  0,  0,  9,  9,  6,  9,  0,
        3,  4,  4,  4,  4,  4,  4,  0,  9,  5, 10, 10, 10, 10, 10,  0,  9,
        8,  5,  0,  9,  0,  5,  8, 15, 10,  4, 10, 10,  4,  3,  3,  0,  8,
       13,  3, 12,  3,  3, 15, 14, 15,  3, 14,  0,  5,  5,  4,  4,  4,  0,
        0,  4,  4,  9,  9,  4,  3,  5,  5,  3,  5,  5, 14,  3,  3, 13,  3,
       12,  4,  4,  3,  4,  4,  3,  3,  3,  0,  3, 13,  7,  6,  7,  8,  8,
        6,  6,  6,  5,  7,  7,  0,  7,  6,  7,  7,  7,  7,  6,  7,  6,  8,
        6,  0,  3,  1,  7,  5,  5,  5,  5,  3,  8,  7,  7,  6,  6, 12,  7,
       11, 16,  1,  0, 16

In [7]:
for i in range(len(set(labels))):
    print("\n\nCLUSTER {} ({} nodes):".format(i, np.sum(labels == i)))
    no = 0
    for j in range(len(labels)):
        if labels[j] == i:
            no += 1
            print(no, annotations[j])







CLUSTER 0 (99 nodes):
1 ordered sets
2 fuzzy sets
3 combinatorial matrices incidence hadamard
4 combinatorial finite geometries
5 combinatorial matroids geometric lattices
6 combinatorial packing covering
7 combinatorial tessellation tiling
8 trees
9 vertex degrees
10 paths cycles
11 connectivity
12 density toughness
13 isomorphism
14 vertex subsets dominating sets independent sets cliques
15 edge subsets factorization matching partitioning covering packing
16 lattices
17 modular lattices complemented lattices
18 linear equations linear algebraic
19 matrix inversion generalized inverses
20 conditioning matrices
21 eigenvalues singular values eigenvectors
22 matrix equations identities
23 inverse linear algebra
24 linear inequalities matrices
25 inequalities involving eigenvalues eigenvectors
26 norms matrices
27 quadratic bilinear forms
28 multilinear algebra tensor calculus
29 vector tensor algebra
30 max-plus algebras
31 orthogonal matrices
32 fuzzy matrices
33 boolean hadamard mat

In [8]:
louvain.membership_

<343x18 sparse matrix of type '<class 'numpy.float64'>'
	with 6174 stored elements in Compressed Sparse Row format>

In [9]:
louvain_membership = louvain.membership_.todense()

In [10]:
np.min(louvain_membership), np.max(louvain_membership)

(0.0028407585896997626, 0.2580979693795769)

In [11]:
louvain_membership[:, 0]

matrix([[0.25529851],
        [0.25554106],
        [0.25537871],
        [0.25549653],
        [0.25664896],
        [0.2563683 ],
        [0.25425743],
        [0.25678278],
        [0.25681227],
        [0.25658282],
        [0.2571108 ],
        [0.25628536],
        [0.25682184],
        [0.25645242],
        [0.25507302],
        [0.25511088],
        [0.2548556 ],
        [0.25528032],
        [0.25525786],
        [0.25479618],
        [0.25419965],
        [0.25553578],
        [0.25516763],
        [0.25677129],
        [0.25630352],
        [0.25627267],
        [0.25601574],
        [0.25563357],
        [0.25636883],
        [0.25511886],
        [0.25478034],
        [0.25664842],
        [0.2561817 ],
        [0.25482405],
        [0.25534986],
        [0.2555986 ],
        [0.25539003],
        [0.25566272],
        [0.25503398],
        [0.25277931],
        [0.25455169],
        [0.25647453],
        [0.25617766],
        [0.25482036],
        [0.25523751],
        [0

In [12]:
for i, cluster in enumerate(np.round(louvain_membership.T, 3)):
    print("CLUSTER {}:\n".format(i + 1))
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")






CLUSTER 1:

[('search', 0.258), ('ordered sets', 0.257), ('combinatorial matrices incidence hadamard', 0.257), ('combinatorial finite geometries', 0.257), ('combinatorial matroids geometric lattices', 0.257), ('combinatorial packing covering', 0.257), ('trees', 0.257), ('paths cycles', 0.257), ('vertex subsets dominating sets independent sets cliques', 0.257), ('inverse linear algebra', 0.257), ('max-plus algebras', 0.257), ('boolean hadamard matrices', 0.257), ('random matrices', 0.257), ('erdos', 0.257), ('packing covering', 0.257)]



CLUSTER 2:

[('graph', 0.084), ('flows graphs', 0.081), ('hypergraphs', 0.08), ('planar graphs', 0.079), ('coloring graphs hypergraphs', 0.079), ('perfect graphs', 0.079), ('directed graphs digraphs', 0.079), ('extremal graph', 0.079), ('random graphs', 0.079), ('mathematical geography demography', 0.079), ('graphical indices', 0.078), ('distance graphs', 0.078), ('signed weighted graphs', 0.078), ('graph labelling graceful graphs bandwidth', 0.078), (

In [13]:
contrib

array([0.99986001])

In [14]:
intensity

matrix([[   950.78705273, 903996.01963852]])

In [15]:
lat

array([903996.01963852])

In [16]:
tc

array([[3354.30257421, 1600.03612393, 1346.1412584 , ..., 3554.6570268 ,
        3625.92911271, 3206.52059489],
       [1600.03612393,  924.78236171,  743.99805078, ..., 1848.82022447,
        1882.50755319, 1669.27688601],
       [1346.1412584 ,  743.99805078,  661.33915235, ..., 1530.43871115,
        1558.05774318, 1382.03052727],
       ...,
       [3554.6570268 , 1848.82022447, 1530.43871115, ..., 4471.98515693,
        4448.29097346, 3769.43880341],
       [3625.92911271, 1882.50755319, 1558.05774318, ..., 4448.29097346,
        4656.84983748, 3848.94711291],
       [3206.52059489, 1669.27688601, 1382.03052727, ..., 3769.43880341,
        3848.94711291, 3609.3195464 ]])

In [17]:
np.linalg.eigh(tc)[0][::-1]

array([9.03996020e+05, 4.20177077e+03, 3.53479355e+03, 3.13773819e+03,
       2.94117148e+03, 2.85488008e+03, 2.51979707e+03, 2.33462507e+03,
       2.11598256e+03, 1.95511311e+03, 1.91221581e+03, 1.74948138e+03,
       1.54002986e+03, 1.48905705e+03, 1.41960020e+03, 1.39476157e+03,
       1.33015034e+03, 1.27906181e+03, 1.21455536e+03, 1.10998730e+03,
       1.05102270e+03, 1.01385712e+03, 1.00801730e+03, 9.69153267e+02,
       9.04981616e+02, 8.87650509e+02, 8.72385184e+02, 8.42372565e+02,
       7.85415993e+02, 7.68649270e+02, 7.50828293e+02, 7.01168528e+02,
       6.73565060e+02, 6.22299098e+02, 5.93948606e+02, 5.71457363e+02,
       5.64745076e+02, 5.10920605e+02, 4.98094595e+02, 4.86928760e+02,
       4.77794312e+02, 4.53842473e+02, 4.29211485e+02, 4.23627239e+02,
       4.20833577e+02, 4.12702442e+02, 3.93018069e+02, 3.80945415e+02,
       3.69304499e+02, 3.55473065e+02, 3.34425040e+02, 3.26954334e+02,
       3.08973771e+02, 3.06365667e+02, 3.01978128e+02, 2.93587966e+02,
      

In [18]:
np.linalg.eigh(tc)[0][::-1][0] / np.linalg.eigh(tc)[0][::-1][-1]

15245078.068472277

In [19]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [20]:
member = np.loadtxt("clusters without lapin.dat")

In [21]:
member.shape

(343,)

In [22]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

CLUSTER:

[('probability inductive logic', 0.058016963541439794)]



CLUSTER:

[('probability inductive logic', 0.030023688419786452)]



CLUSTER:

[('probability inductive logic', 0.02490655943861299)]



CLUSTER:

[('probability inductive logic', 0.07909934028390103)]



CLUSTER:

[('probability inductive logic', 0.038877959421445486)]



CLUSTER:

[('probability inductive logic', 0.01922759893640881)]



CLUSTER:

[('probability inductive logic', 0.08638640150834981)]



CLUSTER:

[('probability inductive logic', 0.04379164880790519)]



CLUSTER:

[('probability inductive logic', 0.04433480655624608)]



CLUSTER:

[('probability inductive logic', 0.04167436506548003)]



CLUSTER:

[('probability inductive logic', 0.04946636122756816)]



CLUSTER:

[('probability inductive logic', 0.056308458318457884)]



CLUSTER:

[('probability inductive logic', 0.03442684920291643)]



CLUSTER:

[('probability inductive logic', 0.03949982441523427)]



CLUSTER:

[('probability inductive logic', 0

In [23]:
member.T

array([0.05801696, 0.03002369, 0.02490656, 0.07909934, 0.03887796,
       0.0192276 , 0.0863864 , 0.04379165, 0.04433481, 0.04167437,
       0.04946636, 0.05630846, 0.03442685, 0.03949982, 0.04612391,
       0.03023616, 0.04496387, 0.03492102, 0.03936295, 0.03505032,
       0.02515072, 0.03528289, 0.03554737, 0.02911145, 0.05001017,
       0.03394528, 0.03954917, 0.04779521, 0.0297122 , 0.07784601,
       0.03304201, 0.04551267, 0.05933517, 0.05392085, 0.05457894,
       0.03426127, 0.03407242, 0.03236072, 0.04833176, 0.02848513,
       0.04185498, 0.04077738, 0.05146764, 0.05779653, 0.05639648,
       0.04953962, 0.07050064, 0.05816931, 0.05712019, 0.0740039 ,
       0.06586881, 0.05283923, 0.05148456, 0.04720051, 0.07476156,
       0.0606929 , 0.06597045, 0.04732968, 0.05278617, 0.04874573,
       0.03815698, 0.05368699, 0.04265614, 0.04096888, 0.03464508,
       0.02594536, 0.0406574 , 0.02882902, 0.0351388 , 0.04167523,
       0.05532189, 0.04070019, 0.04291293, 0.05496207, 0.03324

In [24]:
np.max(member)

0.11457016330185478

In [25]:
np.min(member)

0.01922759893640881

In [26]:
np.histogram(member.flatten())

(array([  8,  31,  78, 122,  63,  27,  11,   2,   0,   1]),
 array([0.0192276 , 0.02876186, 0.03829611, 0.04783037, 0.05736462,
        0.06689888, 0.07643314, 0.08596739, 0.09550165, 0.10503591,
        0.11457016]))

In [27]:
def get_print_top_k_list(U, top_k=10):
    _, n_cl = U.shape
    top_k_list = []
    for i in range(n_cl):
        top_k_list.append(np.argsort(U[: ,i])[::-1][:top_k])
        print(top_k_list[i])
    return top_k_list

In [28]:
top_k_list = get_print_top_k_list(member)

ValueError: not enough values to unpack (expected 2, got 1)

In [ ]:
def print_intersections(top_k_list):
    print('\t\t Intersections')
    for i in range(len(top_k_list)):
        print(f'Cluster {i+1}', end='\t')
        intersections = ''
        for j in range(len(top_k_list )):
            n_common = len(set(top_k_list[i]).intersection(set(top_k_list[j])))
            intersections += f'{n_common} --'
        intersections.strip('-')
        intersections.strip('-')    
        print(intersections)

In [ ]:
print_intersections(top_k_list)