In [1]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

In [2]:
len(annotations), len(set(annotations))

(343, 343)

In [3]:
import numpy as np
from lapin import lapin
from faddis_zhirayr import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    tc = np.loadtxt("corelevance_matrix.txt")
    print(tc.shape)

    tc_transformed = lapin(tc)
    B, member, contrib, intensity, lat, tt = faddis(tc_transformed)
    np.savetxt("clusters.dat", member)
    print(member.shape)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for i, cluster in enumerate(np.round(member.T, 3)):
        print("CLUSTER {}:\n".format(i + 1))
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])
        print("\n\n")

(343, 343)
Cluster contribution is too small
(343, 7)
CLUSTER 1:

[('stochastic difference equations', 0.939), ('hypothesis testing multivariate analysis', 0.261), ('fuzzy matrices', 0.154), ('random fields image analysis', 0.105), ('information geometry statistical', 0.041), ('packing covering', 0.037), ('combinatorial probability', 0.031), ('fuzziness design statistical experiments', 0.031), ('computational data analysis big data', 0.031), ('linear programming', 0.03), ('fuzzy analysis statistics', 0.026), ('combinatorial matroids geometric lattices', 0.025), ('numerical mathematical programming', 0.023), ('estimation survival analysis censored data', 0.021), ('random matrices', 0.02)]



CLUSTER 2:

[('fuzzy difference equations', 0.91), ('applications statistics', 0.224), ('image analysis multivariate analysis', 0.136), ('computational data analysis big data', 0.127), ('stochastic matrices', 0.107), ('hypothesis testing', 0.087), ('packing covering', 0.084), ('stochastic difference

In [4]:
contrib

array([0.00282526, 0.00266069, 0.00244581, 0.00231539, 0.00216621,
       0.00210793, 0.00197254])

In [5]:
intensity

matrix([[0.99157653, 0.98322401],
        [0.97681003, 0.95415784],
        [0.9564609 , 0.91481745],
        [0.94344759, 0.89009336],
        [0.92786934, 0.86094151],
        [0.92156426, 0.84928069],
        [0.90639583, 0.82155341]])

In [6]:
lat

array([1.00000005, 1.00000011, 1.00000024, 1.00000029, 1.00002042,
       1.00061221, 1.00000247])

In [7]:
tc

array([[3354.30257421, 1600.03612393, 1346.1412584 , ..., 3554.6570268 ,
        3625.92911271, 3206.52059489],
       [1600.03612393,  924.78236171,  743.99805078, ..., 1848.82022447,
        1882.50755319, 1669.27688601],
       [1346.1412584 ,  743.99805078,  661.33915235, ..., 1530.43871115,
        1558.05774318, 1382.03052727],
       ...,
       [3554.6570268 , 1848.82022447, 1530.43871115, ..., 4471.98515693,
        4448.29097346, 3769.43880341],
       [3625.92911271, 1882.50755319, 1558.05774318, ..., 4448.29097346,
        4656.84983748, 3848.94711291],
       [3206.52059489, 1669.27688601, 1382.03052727, ..., 3769.43880341,
        3848.94711291, 3609.3195464 ]])

In [8]:
np.linalg.eigh(tc)[0][::-1]

array([9.03996020e+05, 4.20177077e+03, 3.53479355e+03, 3.13773819e+03,
       2.94117148e+03, 2.85488008e+03, 2.51979707e+03, 2.33462507e+03,
       2.11598256e+03, 1.95511311e+03, 1.91221581e+03, 1.74948138e+03,
       1.54002986e+03, 1.48905705e+03, 1.41960020e+03, 1.39476157e+03,
       1.33015034e+03, 1.27906181e+03, 1.21455536e+03, 1.10998730e+03,
       1.05102270e+03, 1.01385712e+03, 1.00801730e+03, 9.69153267e+02,
       9.04981616e+02, 8.87650509e+02, 8.72385184e+02, 8.42372565e+02,
       7.85415993e+02, 7.68649270e+02, 7.50828293e+02, 7.01168528e+02,
       6.73565060e+02, 6.22299098e+02, 5.93948606e+02, 5.71457363e+02,
       5.64745076e+02, 5.10920605e+02, 4.98094595e+02, 4.86928760e+02,
       4.77794312e+02, 4.53842473e+02, 4.29211485e+02, 4.23627239e+02,
       4.20833577e+02, 4.12702442e+02, 3.93018069e+02, 3.80945415e+02,
       3.69304499e+02, 3.55473065e+02, 3.34425040e+02, 3.26954334e+02,
       3.08973771e+02, 3.06365667e+02, 3.01978128e+02, 2.93587966e+02,
      

In [9]:
np.linalg.eigh(tc)[0][::-1][0] / np.linalg.eigh(tc)[0][::-1][-1]

15245078.068472277

In [10]:
np.linalg.eigh(lapin(tc))[0][::-1]

array([1.00473171e+00, 1.00369628e+00, 1.00351957e+00, 1.00335154e+00,
       1.00295444e+00, 1.00283813e+00, 1.00255286e+00, 1.00248273e+00,
       1.00227666e+00, 1.00207262e+00, 1.00194184e+00, 1.00184165e+00,
       1.00171603e+00, 1.00158810e+00, 1.00154939e+00, 1.00146548e+00,
       1.00141499e+00, 1.00131420e+00, 1.00127400e+00, 1.00121360e+00,
       1.00113422e+00, 1.00111206e+00, 1.00106775e+00, 1.00102300e+00,
       1.00099977e+00, 1.00095976e+00, 1.00093545e+00, 1.00087755e+00,
       1.00087064e+00, 1.00083885e+00, 1.00077085e+00, 1.00074252e+00,
       1.00073461e+00, 1.00069928e+00, 1.00066557e+00, 1.00065195e+00,
       1.00061437e+00, 1.00058195e+00, 1.00055716e+00, 1.00054038e+00,
       1.00052037e+00, 1.00050251e+00, 1.00049041e+00, 1.00047530e+00,
       1.00045336e+00, 1.00044426e+00, 1.00043766e+00, 1.00043533e+00,
       1.00042096e+00, 1.00040094e+00, 1.00039192e+00, 1.00037610e+00,
       1.00036949e+00, 1.00035975e+00, 1.00034254e+00, 1.00033920e+00,
      

In [11]:
np.savetxt("corelevance_matrix_lapin.txt", tc_transformed)

In [12]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [13]:
member = np.loadtxt("clusters.dat")

In [14]:
member.shape

(343, 7)

In [15]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

CLUSTER:

[('stochastic difference equations', 0.9392964969964227), ('hypothesis testing multivariate analysis', 0.2611588206615198), ('fuzzy matrices', 0.15383732194012517), ('random fields image analysis', 0.10513017874465339), ('information geometry statistical', 0.04083891799618715), ('packing covering', 0.037385594562387624), ('computational data analysis big data', 0.03147111109797983), ('combinatorial probability', 0.03127681505670111), ('fuzziness design statistical experiments', 0.030899518167011163), ('linear programming', 0.029641227521658257), ('fuzzy analysis statistics', 0.02602991265768288), ('combinatorial matroids geometric lattices', 0.02536025640211493), ('numerical mathematical programming', 0.023377462282849575), ('estimation survival analysis censored data', 0.021469517628252218), ('markov processes hypothesis testing', 0.020424332563427874)]



CLUSTER:

[('fuzzy difference equations', 0.909832099396069), ('applications statistics', 0.22367943170023796), ('image 

In [16]:
member.T

array([[0.00000000e+00, 6.01415498e-05, 2.66932238e-03, ...,
        0.00000000e+00, 0.00000000e+00, 5.59705079e-04],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.11859083e-03, 1.09968658e-03, 0.00000000e+00, ...,
        1.52176780e-01, 1.47625734e-02, 0.00000000e+00],
       ...,
       [2.73589060e-02, 0.00000000e+00, 6.66352512e-02, ...,
        0.00000000e+00, 1.87489982e-03, 3.45922275e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.09495037e-02, 0.00000000e+00, 0.00000000e+00],
       [1.13375730e-02, 0.00000000e+00, 8.09890984e-03, ...,
        0.00000000e+00, 2.23934334e-02, 1.40659847e-03]])

In [17]:
np.max(member)

0.9392964969964227

In [18]:
np.min(member)

0.0

In [19]:
np.histogram(member.flatten())

(array([2333,   44,   10,    5,    1,    0,    4,    2,    0,    2]),
 array([0.        , 0.09392965, 0.1878593 , 0.28178895, 0.3757186 ,
        0.46964825, 0.5635779 , 0.65750755, 0.7514372 , 0.84536685,
        0.9392965 ]))

In [20]:
def get_print_top_k_list(U, top_k=10):
    _, n_cl = U.shape
    top_k_list = []
    for i in range(n_cl):
        top_k_list.append(np.argsort(U[: ,i])[::-1][:top_k])
        print(top_k_list[i])
    return top_k_list

In [21]:
top_k_list = get_print_top_k_list(member)

[ 79 133  67 162 105  82 240  87 154 284]
[ 78 170 139 240  71 117  82  79 140 105]
[ 10  88 186 204 108 162 132 340  78 170]
[164 139 133 154  96 306 169 240 114 181]
[ 81 305 127 293 280 126  65 318  62 227]
[276 291 103 296 107 109  85 245  58 223]
[130 157 210 253 169 162  51  77 188 316]


In [22]:
def print_intersections(top_k_list):
    print('\t\t Intersections')
    for i in range(len(top_k_list)):
        print(f'Cluster {i+1}', end='\t')
        intersections = ''
        for j in range(len(top_k_list )):
            n_common = len(set(top_k_list[i]).intersection(set(top_k_list[j])))
            intersections += f'{n_common} --'
        intersections.strip('-')
        intersections.strip('-')    
        print(intersections)

In [23]:
print_intersections(top_k_list)

		 Intersections
Cluster 1	10 --4 --1 --3 --0 --0 --1 --
Cluster 2	4 --10 --2 --2 --0 --0 --0 --
Cluster 3	1 --2 --10 --0 --0 --0 --1 --
Cluster 4	3 --2 --0 --10 --0 --0 --1 --
Cluster 5	0 --0 --0 --0 --10 --0 --0 --
Cluster 6	0 --0 --0 --0 --0 --10 --0 --
Cluster 7	1 --0 --1 --1 --0 --0 --10 --
