In [1]:
import numpy as np
from lapin import lapin
from faddis_zhirayr import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    tc = np.loadtxt("corelevance_matrix.txt")
    print(tc.shape)

    tc_transformed = lapin(tc)
    B, member, contrib, intensity, lat, tt = faddis(tc_transformed)
    np.savetxt("clusters.dat", member)
    print(member.shape)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for i, cluster in enumerate(np.round(member.T, 3)):
        print("CLUSTER {}:\n".format(i + 1))
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])
        print("\n\n")

(317, 317)
Cluster contribution is too small
(317, 14)
CLUSTER 1:

[('query representation', 0.949), ('distributed database recovery', 0.295), ('data locking', 0.108), ('reinforcement learning theory', 0.005), ('web log analysis', 0.004), ('multi-agent learning', 0.003), ('language models', 0.003), ('learning to rank', 0.003), ('supervised learning by classification', 0.003), ('active learning', 0.002), ('network data models', 0.002), ('document structure', 0.002), ('video segmentation', 0.002), ('topic modeling', 0.002), ('online learning settings', 0.002)]



CLUSTER 2:

[('active learning settings', 0.647), ('online learning theory', 0.535), ('multi-agent reinforcement learning', 0.518), ('query learning', 0.143), ('inverse reinforcement learning', 0.046), ('learning to rank', 0.036), ('mixture modeling', 0.02), ('lifelong machine learning', 0.017), ('statistical relational learning', 0.015), ('object detection', 0.014), ('speech recognition', 0.013), ('online analytical processing 

In [2]:
contrib

array([0.0031149 , 0.00300115, 0.00290139, 0.00277625, 0.00269503,
       0.00263296, 0.00255424, 0.0025022 , 0.00244303, 0.00240134,
       0.00231523, 0.00223002, 0.00207853, 0.00199784])

In [3]:
intensity

matrix([[0.9962047 , 0.9924238 ],
        [0.98698267, 0.9741348 ],
        [0.97867627, 0.95780724],
        [0.96794869, 0.93692466],
        [0.96078993, 0.92311729],
        [0.95520918, 0.91242458],
        [0.94798803, 0.89868131],
        [0.9431225 , 0.88948004],
        [0.93749677, 0.87890019],
        [0.93347154, 0.87136911],
        [0.92498823, 0.85560322],
        [0.91635705, 0.83971024],
        [0.90038153, 0.81068691],
        [0.89151254, 0.79479461]])

In [4]:
lat

array([1.00000002, 1.00000015, 1.00000032, 1.005582  , 1.0000049 ,
       1.00110879, 1.00019845, 1.00000003, 1.00313359, 1.00000098,
       1.00099506, 1.00378217, 1.00178688, 1.00090281])

In [5]:
tc

array([[2305.0814415 , 3051.74081109, 2419.97985005, ..., 2702.02572888,
        1833.74858063, 2071.55138414],
       [3051.74081109, 4458.59457895, 3484.23240944, ..., 3903.01060014,
        2493.31161151, 2957.11046645],
       [2419.97985005, 3484.23240944, 2935.31079589, ..., 3104.19581913,
        1979.45360701, 2357.2419839 ],
       ...,
       [2702.02572888, 3903.01060014, 3104.19581913, ..., 3791.35716949,
        2209.7986961 , 2656.0674004 ],
       [1833.74858063, 2493.31161151, 1979.45360701, ..., 2209.7986961 ,
        1662.18167924, 1706.75366935],
       [2071.55138414, 2957.11046645, 2357.2419839 , ..., 2656.0674004 ,
        1706.75366935, 2254.21414074]])

In [6]:
np.linalg.eigh(tc)[0][::-1]

array([6.14806125e+05, 2.94476028e+03, 2.74563326e+03, 2.62436189e+03,
       2.02967532e+03, 1.92706980e+03, 1.85074257e+03, 1.82368666e+03,
       1.43701574e+03, 1.35390206e+03, 1.12456386e+03, 1.05698324e+03,
       1.02216606e+03, 9.76450849e+02, 8.84878841e+02, 8.15280263e+02,
       7.81835859e+02, 7.31321415e+02, 7.14352494e+02, 6.82892432e+02,
       6.71866106e+02, 5.72060566e+02, 5.56350591e+02, 5.48160323e+02,
       5.36251179e+02, 5.22039841e+02, 5.00172882e+02, 4.87716133e+02,
       4.65557050e+02, 4.55694087e+02, 4.43543852e+02, 4.33244907e+02,
       4.19490312e+02, 4.14999532e+02, 4.05246632e+02, 3.98248694e+02,
       3.80761613e+02, 3.62362772e+02, 3.52562176e+02, 3.35754934e+02,
       3.29620694e+02, 3.26763627e+02, 3.05827061e+02, 3.00701110e+02,
       2.89714853e+02, 2.88189012e+02, 2.83014895e+02, 2.73388672e+02,
       2.67739992e+02, 2.57634808e+02, 2.54888677e+02, 2.50398648e+02,
       2.43121980e+02, 2.41566665e+02, 2.34832228e+02, 2.29120968e+02,
      

In [8]:
6.14806125e+05 /  3.79006210e-13

1.6221531699968717e+18

In [7]:
np.linalg.eigh(lapin(tc))[0][::-1]

array([1.00565814e+00, 1.00471718e+00, 1.00380051e+00, 1.00376586e+00,
       1.00333809e+00, 1.00315287e+00, 1.00281793e+00, 1.00263133e+00,
       1.00227379e+00, 1.00195386e+00, 1.00184711e+00, 1.00182035e+00,
       1.00174200e+00, 1.00155708e+00, 1.00135567e+00, 1.00134468e+00,
       1.00133233e+00, 1.00126414e+00, 1.00120822e+00, 1.00113845e+00,
       1.00110976e+00, 1.00104842e+00, 1.00100322e+00, 1.00096274e+00,
       1.00092248e+00, 1.00091354e+00, 1.00089534e+00, 1.00088008e+00,
       1.00085788e+00, 1.00084628e+00, 1.00080316e+00, 1.00078019e+00,
       1.00073982e+00, 1.00073663e+00, 1.00071978e+00, 1.00068180e+00,
       1.00066275e+00, 1.00062245e+00, 1.00061378e+00, 1.00060677e+00,
       1.00059156e+00, 1.00058402e+00, 1.00055688e+00, 1.00054197e+00,
       1.00052596e+00, 1.00052218e+00, 1.00049998e+00, 1.00049099e+00,
       1.00048170e+00, 1.00047745e+00, 1.00046721e+00, 1.00046072e+00,
       1.00043845e+00, 1.00043596e+00, 1.00042123e+00, 1.00040456e+00,
      

In [15]:
np.savetxt("corelevance_matrix_lapin.txt", tc_transformed)

In [2]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [3]:
member = np.loadtxt("clusters.dat")

In [4]:
member.shape

(317, 3)

In [5]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

CLUSTER:

[('query representation', 0.9492738808638721), ('distributed database recovery', 0.2952466254141227), ('data locking', 0.10766606850706567), ('reinforcement learning theory', 0.004788322615586317), ('web log analysis', 0.0035142409368013098), ('multi-agent learning', 0.0032362405117119467), ('learning to rank', 0.0029917827381894125), ('language models', 0.002930889077737563), ('supervised learning by classification', 0.002519422410168774), ('online learning settings', 0.0023864710609815547), ('network data models', 0.0017331426620566376), ('active learning', 0.001682660905651917), ('document structure', 0.0016760969324413695), ('video segmentation', 0.0016273449249671603), ('topic modeling', 0.0016255370971410311)]



CLUSTER:

[('active learning settings', 0.646887145506174), ('online learning theory', 0.5350419077372148), ('multi-agent reinforcement learning', 0.5177446381440173), ('query learning', 0.14309190122171475), ('inverse reinforcement learning', 0.046179521538707

In [6]:
member.T

array([[4.08910680e-04, 1.35489999e-04, 8.63217289e-04, 0.00000000e+00,
        0.00000000e+00, 7.10508460e-04, 3.90989627e-04, 0.00000000e+00,
        3.23624051e-03, 1.14446480e-03, 0.00000000e+00, 0.00000000e+00,
        4.78832262e-03, 1.68266091e-03, 0.00000000e+00, 0.00000000e+00,
        8.68742679e-05, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 1.95653253e-05, 0.00000000e+00, 1.75091902e-04,
        1.24532335e-04, 4.44298174e-04, 0.00000000e+00, 4.29450223e-04,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.39042634e-05, 2.82979320e-04,
        4.43231924e-04, 3.73227300e-04, 6.63609910e-05, 0.00000000e+00,
        8.39760838e-06, 0.00000000e+00, 2.89611607e-05, 0.00000000e+00,
        4.44328261e-04, 7.66840189e-05, 1.46153597e-04, 1.03275667e-04,
        1.93941830e-04, 3.43727534e-05, 4.48784509e-05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 4.94620677e-04, 0.000000

In [7]:
np.max(member)

0.9492738808638721

In [8]:
np.min(member)

0.0

In [9]:
np.histogram(member.flatten())

(array([935,   7,   1,   2,   0,   3,   1,   1,   0,   1]),
 array([0.        , 0.09492739, 0.18985478, 0.28478216, 0.37970955,
        0.47463694, 0.56956433, 0.66449172, 0.7594191 , 0.85434649,
        0.94927388]))