In [ ]:
import numpy as np
from lapin import lapin
from faddis import faddis

from operator import itemgetter

NUM_EL = 15
alpha = 0.2


if __name__ == "__main__":
    relevance_matrix = np.loadtxt("relevance_matrix.txt").T
    print(relevance_matrix.shape)

    rm_threshold = relevance_matrix > alpha
    abstract_threshold_count = np.sum(rm_threshold, axis=0)
    max_threshold_count = max(abstract_threshold_count)
    abstract_weight = max_threshold_count / abstract_threshold_count
    W = np.diag(abstract_weight)

    tc = relevance_matrix.dot(W).dot(relevance_matrix.T)
    print(tc.shape)

    tc_transformed = lapin(tc)
    B, member, contrib, intensity, lat, tt = faddis(tc_transformed)
    np.savetxt("clusters.dat", member)

    with open("taxonomy_leaves.txt") as fn:
        annotations = [l.strip() for l in fn]

    for cluster in member.T:
        print(list(sorted(zip(annotations, cluster.flat),
                          key=itemgetter(1), reverse=True))[:NUM_EL])

In [18]:
import numpy as np
from operator import itemgetter
NUM_EL = 15

In [19]:
member = np.loadtxt("clusters.dat")

In [20]:
member.shape

(352, 3)

In [21]:
with open("taxonomy_leaves.txt") as fn:
    annotations = [l.strip() for l in fn]

for cluster in member.T:
    print("CLUSTER:\n")
    print(list(sorted(zip(annotations, cluster.flat),
                      key=itemgetter(1), reverse=True))[:NUM_EL])
    print("\n\n")

CLUSTER:

[('data provenance', 0.4707643721456703), ('apprenticeship learning', 0.3251215365531277), ('information extraction', 0.31832054040261576), ('data exchange', 0.3005460919901672), ('sequential decision making', 0.28630313045725053), ('adversarial learning', 0.2731795995912557), ('gaussian processes', 0.258476513567086), ('multi-agent reinforcement learning', 0.23603420039691167), ('markov decision processes', 0.21608407632075977), ('boosting', 0.20287614009695887), ('2d pca', 0.20198232433172436), ('data cleaning', 0.1709956853629661), ('distributed database recovery', 0.159762043876654), ('cluster analysis', 0.10188978867578631), ('data locking', 0.05812390045299409)]



CLUSTER:

[('data provenance', 0.4733135907761032), ('apprenticeship learning', 0.3254410743435387), ('information extraction', 0.31925100459129224), ('data exchange', 0.3017354667013574), ('sequential decision making', 0.2873979631674248), ('adversarial learning', 0.2733960219312089), ('gaussian processes', 

In [5]:
member.T

array([[0.00000000e+00, 1.22769209e-12, 9.70496189e-11, ...,
        6.16375164e-11, 1.89891019e-12, 4.14235425e-12],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [6]:
np.max(member)

0.4733135907761032

In [7]:
np.min(member)

0.0

In [12]:
np.histogram(member.flatten())

(array([1010,    3,    5,    4,   12,    8,   10,    1,    0,    3]),
 array([0.        , 0.04733136, 0.09466272, 0.14199408, 0.18932544,
        0.2366568 , 0.28398815, 0.33131951, 0.37865087, 0.42598223,
        0.47331359]))

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.22769209e-12, 0.00000000e+00, 0.00000000e+00],
       [9.70496189e-11, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.16375164e-11, 0.00000000e+00, 0.00000000e+00],
       [1.89891019e-12, 0.00000000e+00, 0.00000000e+00],
       [4.14235425e-12, 0.00000000e+00, 0.00000000e+00]])

In [1]:
import numpy as np

NUM_EL = 15
alpha = 0.2


relevance_matrix = np.loadtxt("relevance_matrix.txt").T
print(relevance_matrix.shape)

rm_threshold = relevance_matrix > alpha
abstract_threshold_count = np.sum(rm_threshold, axis=0)
max_threshold_count = max(abstract_threshold_count)
abstract_weight = max_threshold_count / abstract_threshold_count
W = np.diag(abstract_weight)


(352, 32632)


In [8]:
rm_threshold = relevance_matrix > 0.33
abstract_threshold_count = np.sum(rm_threshold, axis=0)

In [9]:
abstract_threshold_count

array([ 7, 13, 19, ...,  8,  4,  3])

In [10]:
np.min(abstract_threshold_count), np.max(abstract_threshold_count)

(0, 37)

In [11]:
np.sum(abstract_threshold_count == 0)

145

In [12]:
len(abstract_threshold_count)

32632